export async function up(knex) {
  await knex.schema.createTable('lead_creation_requests', (table) => {
    table.bigIncrements('id');

    table
      .bigInteger('actor_id')
      .unsigned()
      .notNullable()
      .references('id')
      .inTable('users')
      .onDelete('RESTRICT');

    /*
     * UUID generated by the frontend for one submission.
     * Retries reuse the same key.
     */
    table.string('request_key', 36).notNullable();

    /*
     * SHA-256 of the validated, normalized request.
     * Reusing a key with different data must return a conflict.
     */
    table.string('payload_hash', 64).notNullable();

    /*
     * Initially null inside the creation transaction.
     * Set before committing the lead and its related records.
     */
    table
      .bigInteger('lead_id')
      .unsigned()
      .nullable()
      .references('id')
      .inTable('leads')
      .onDelete('RESTRICT');

    table
      .dateTime('created_at', { precision: 3 })
      .notNullable()
      .defaultTo(knex.raw('CURRENT_TIMESTAMP(3)'));

    table.unique(
      ['actor_id', 'request_key'],
      'lead_creation_requests_actor_key_unique',
    );
  });
}

export async function down(knex) {
  await knex.schema.dropTableIfExists('lead_creation_requests');
}